import type { HomepageCmsData } from './homepage-cms';

// Static fallback data when Strapi CMS is unavailable
// This data mirrors the CMS structure and matches the locale content

export const staticHomepageDataEn: HomepageCmsData = {
  hero: {
    titleLine1: 'INVESTING',
    titleLine2: 'BEYOND',
    titleLine3: 'THE OBVIOUS',
    ctaLabel: 'Dive Deeper',
    ctaUrl: '#',
    image: '/assets/hero.jpg',
    alt: 'Architectural Background',
  },
  legacySection: {
    headingLine1: 'WHERE LEGACY',
    headingLine2: 'BECOMES PRESENCE',
    description: '',
    image: '/assets/horse.jpg',
    alt: 'Horses',
    ctaLabel: 'Learn More',
    ctaUrl: '#',
  },
  globalHeadingLine1: 'A GLOBAL PRESENCE',
  globalHeadingLine2: 'QUIETLY POWERFUL',
  globalSlides: [
    {
      id: 1,
      img: '/assets/45.jpg',
      title: 'UNITED STATES OF AMERICA',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'UNITED STATES OF AMERICA',
    },
    {
      id: 2,
      img: '/assets/20.jpg',
      title: 'ANOTHER REGION',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'ANOTHER REGION',
    },
    {
      id: 3,
      img: '/assets/20.jpg',
      title: 'ANOTHER REGION 2',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'ANOTHER REGION 2',
    },
    {
      id: 4,
      img: '/assets/20.jpg',
      title: 'ANOTHER REGION 3',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'ANOTHER REGION 3',
    },
    {
      id: 5,
      img: '/assets/20.jpg',
      title: 'ANOTHER REGION 4',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'ANOTHER REGION 4',
    },
    {
      id: 6,
      img: '/assets/20.jpg',
      title: 'ANOTHER REGION 5',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'ANOTHER REGION 5',
    },
    {
      id: 7,
      img: '/assets/20.jpg',
      title: 'ANOTHER REGION 6',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.',
      alt: 'ANOTHER REGION 6',
    },
  ],
  sectorsHeadingLine1: 'THE SECTORS THAT',
  sectorsHeadingLine2: 'SHAPE TOMORROW',
  featuredSector: {
    title: 'PRIVATE EQUITY &\nGROWTH',
    description: '',
    image: '/assets/private-equity.png',
    alt: 'PRIVATE EQUITY & GROWTH',
    ctaLabel: 'Read More',
    ctaUrl: '#',
  },
  sectorsOfFocusHeading: 'SECTORS OF FOCUS',
  sectorsOfFocusItems: [
    {
      id: 1,
      img: '/assets/skyline.png',
      title: 'TECHNOLOGY & AI',
      alt: 'TECHNOLOGY & AI',
    },
    {
      id: 2,
      img: '/assets/skyline.png',
      title: 'FINANCIAL SERVICES & FINTECH',
      alt: 'FINANCIAL SERVICES & FINTECH',
    },
    {
      id: 3,
      img: '/assets/skyline.png',
      title: 'INFRASTRUCTURE',
      alt: 'INFRASTRUCTURE',
    },
    {
      id: 4,
      img: '/assets/skyline.png',
      title: 'HEALTHCARE & BIOTECH',
      alt: 'HEALTHCARE & BIOTECH',
    },
    {
      id: 5,
      img: '/assets/skyline.png',
      title: 'ENERGY & SUSTAINABILITY',
      alt: 'ENERGY & SUSTAINABILITY',
    },
    {
      id: 6,
      img: '/assets/skyline.png',
      title: 'REAL ESTATE & LOGISTICS',
      alt: 'REAL ESTATE & LOGISTICS',
    },
  ],
  partnershipHeading: 'A DIFFERENT KIND OF PARTNERSHIP',
  partnerLogos: [
    {
      id: 1,
      name: 'Guggenheim',
      logo: '/assets/gh-logo.png',
      websiteUrl: '#',
    },
    {
      id: 2,
      name: 'SpaceX',
      logo: '/assets/spacex-logo.png',
      websiteUrl: '#',
    },
    {
      id: 3,
      name: 'OpenAI',
      logo: '/assets/openai-logo.png',
      websiteUrl: '#',
    },
    {
      id: 4,
      name: 'Lambda',
      logo: '/assets/lambda-logo.png',
      websiteUrl: '#',
    },
  ],
  partnerCta: {
    title: 'PARTNER WITH US',
    description: 'We collaborate with partners who share our commitment to creating long-term value. If you are building something meant to last, we are ready to build with you.',
    buttonLabel: 'Get in touch',
    buttonUrl: '/en/contact-us',
  },
};

export const staticHomepageDataAr: HomepageCmsData = {
  hero: {
    titleLine1: 'استثمار',
    titleLine2: 'ما وراء',
    titleLine3: 'المألوف',
    ctaLabel: 'اكتشف المزيد',
    ctaUrl: '#',
    image: '/assets/hero.jpg',
    alt: 'خلفية معمارية',
  },
  legacySection: {
    headingLine1: 'حيث يصبح الإرث',
    headingLine2: 'حضوراً',
    description: '',
    image: '/assets/horse.jpg',
    alt: 'خيول',
    ctaLabel: 'اعرف المزيد',
    ctaUrl: '#',
  },
  globalHeadingLine1: 'حضور عالمي',
  globalHeadingLine2: 'بقوة هادئة',
  globalSlides: [
    {
      id: 1,
      img: '/assets/45.jpg',
      title: 'الولايات المتحدة الأمريكية',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'الولايات المتحدة الأمريكية',
    },
    {
      id: 2,
      img: '/assets/20.jpg',
      title: 'منطقة أخرى',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'منطقة أخرى',
    },
    {
      id: 3,
      img: '/assets/20.jpg',
      title: 'منطقة أخرى ٢',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'منطقة أخرى ٢',
    },
    {
      id: 4,
      img: '/assets/20.jpg',
      title: 'منطقة أخرى ٣',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'منطقة أخرى ٣',
    },
    {
      id: 5,
      img: '/assets/20.jpg',
      title: 'منطقة أخرى ٤',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'منطقة أخرى ٤',
    },
    {
      id: 6,
      img: '/assets/20.jpg',
      title: 'منطقة أخرى ٥',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'منطقة أخرى ٥',
    },
    {
      id: 7,
      img: '/assets/20.jpg',
      title: 'منطقة أخرى ٦',
      description: 'لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسينغ إليت، سيد ديام نونومي نيبه يوسمود تينسيدونت أوت لوريت.',
      alt: 'منطقة أخرى ٦',
    },
  ],
  sectorsHeadingLine1: 'القطاعات التي',
  sectorsHeadingLine2: 'تشكل الغد',
  featuredSector: {
    title: 'الملكية الخاصة\nوالنمو',
    description: '',
    image: '/assets/private-equity.png',
    alt: 'الملكية الخاصة والنمو',
    ctaLabel: 'اقرأ المزيد',
    ctaUrl: '#',
  },
  sectorsOfFocusHeading: 'قطاعات التركيز',
  sectorsOfFocusItems: [
    {
      id: 1,
      img: '/assets/skyline.png',
      title: 'التكنولوجيا والذكاء الاصطناعي',
      alt: 'التكنولوجيا والذكاء الاصطناعي',
    },
    {
      id: 2,
      img: '/assets/skyline.png',
      title: 'الخدمات المالية والتكنولوجيا المالية',
      alt: 'الخدمات المالية والتكنولوجيا المالية',
    },
    {
      id: 3,
      img: '/assets/skyline.png',
      title: 'البنية التحتية',
      alt: 'البنية التحتية',
    },
    {
      id: 4,
      img: '/assets/skyline.png',
      title: 'الرعاية الصحية والتكنولوجيا الحيوية',
      alt: 'الرعاية الصحية والتكنولوجيا الحيوية',
    },
    {
      id: 5,
      img: '/assets/skyline.png',
      title: 'الطاقة والاستدامة',
      alt: 'الطاقة والاستدامة',
    },
    {
      id: 6,
      img: '/assets/skyline.png',
      title: 'العقارات واللوجستيات',
      alt: 'العقارات واللوجستيات',
    },
  ],
  partnershipHeading: 'شراكة من نوع مختلف',
  partnerLogos: [
    {
      id: 1,
      name: 'غوغنهايم',
      logo: '/assets/gh-logo.png',
      websiteUrl: '#',
    },
    {
      id: 2,
      name: 'سبيس إكس',
      logo: '/assets/spacex-logo.png',
      websiteUrl: '#',
    },
    {
      id: 3,
      name: 'أوبن أيه آي',
      logo: '/assets/openai-logo.png',
      websiteUrl: '#',
    },
    {
      id: 4,
      name: 'لامبدا',
      logo: '/assets/lambda-logo.png',
      websiteUrl: '#',
    },
  ],
  partnerCta: {
    title: 'شاركنا',
    description: 'نتعاون مع شركاء يشاركوننا التزامنا بإيجاد قيمة طويلة الأمد. إذا كنت تبني شيئاً يدوم، فنحن مستعدون للبناء معك.',
    buttonLabel: 'تواصل معنا',
    buttonUrl: '/ar/contact-us',
  },
};

export const getStaticHomepageData = (locale: string): HomepageCmsData => {
  return locale === 'ar' ? staticHomepageDataAr : staticHomepageDataEn;
};
